[package]
name = "cargo-espflash"
version = "1.1.0"
authors = [
    "Robin Appelman <robin@icewind.nl>",
    "Jesse Braham <jesse@beta7.io>",
]
edition = "2018"
rust-version = "1.56"
description = "Cargo subcommand for flashing Espressif devices over serial"
repository = "https://github.com/esp-rs/espflash"
license = "GPL-2.0"
keywords = [
    "cargo",
    "cli",
    "embedded",
    "esp",
    "xtensa",
]
categories = [
    "command-line-utilities",
    "development-tools",
    "development-tools::cargo-plugins",
    "embedded",
]

[dependencies]
cargo_metadata = "0.14"
cargo_toml = "0.10"
clap = "3.0.0-rc.1"
clap_derive = "3.0.0-rc.1"
crossterm = "0.22"
espflash = { version = "1", path = "../espflash" }
miette = { version = "3", features = ["fancy"] }
serde = { version = "1", features = ["derive"] }
toml = "0.5"
thiserror = "1"

[package.metadata.binstall]
pkg-url = "{ repo }/releases/download/v{ version }/{ name }"
pkg-fmt = "bin"
